### ISSUE TITLE
[Bug] Cannot find dist directory

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web-react#370]
I want to use TopAppBarFixedAdjust feature.
So I update my version from 0.5.0 to 0.6.0.
In 0.6.0 version doesn't have "dist" directory and I cannot use it.
Can you check this please?

Thank you for read :)

**Comment by moog16** [comment]
It was missing the /dist folder. We added tests https://github.com/material-components/material-components-web-react/pull/320 so this never happens again. I pushed a change so that we can publish. Should be fixed once https://github.com/material-components/material-components-web-react/pull/371 is merged.

**Comment by TroyTae** [comment]
@moog16 
Thank you for your quick response!

**Comment by moog16** [comment]
fixed!
