### ISSUE TITLE
TabBar / Tab issues

### ISSUE THREAD

**Issue by pladaria** [material-components/material-components-web-react#409]
Hi, 

I'm happy to see material components in React. I've been playing with some components and I've detected several issues in tab components:

* `activeIndex` is used to set component initial state and after that it is ignored. This looks like a bad controlled component (props should be the source of truth for controlled components).
* Ripple animation is fired twice

I've been unable to reproduce [these examples](https://material-components.github.io/material-components-web-catalog/#/component/tabs) using react.  Perhaps I'm doing something wrong, some examples would be appreciated.

**Comment by pladaria** [comment]
I've created a codesandox to reproduce those problems. The code is taken from `react-tab-bar` README

https://codesandbox.io/s/3v9xz998v1

To reproduce the double ripple issue, open codesandbox preview in new page, open dev tools and set a mobile viewport

**Comment by moog16** [comment]
@pladaria thanks for opening the issue...RE `activeIndex`, you can programmatically update the activeIndex and the `componentDidUpdate` will catch that change. https://github.com/material-components/material-components-web-react/blame/master/packages/tab-bar/index.js#L32
So I'm not sure what you mean by that issue, but I did find a different issue, which I have a fix for.

RE: double ripple - I do see that, and will also be fixing. Strange that its happening, but maybe its because there is a touch event as well.
