### ISSUE TITLE
External contributions failing in CI

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#71]
External contributors will always have PRs with failing tests. This is due to no having access to GCP, which stores our screenshots.

**Comment by lynnjepsen** [comment]
The short term fix is to following

- [ ] Check if the MDC_GCLOUD_SERVICE_ACCOUNT_KEY environment variable exists...if it does NOT, then don't try and upload any snapshots or diffs to GCP 
- [ ] Make sure running tests without MDC_GCLOUD_SERVICE_ACCOUNT_KEY can still download images

This will make it so that external contributor PRs (which don't affect screenshots, like a JS update or a doc update) will pass travis CI

**Comment by moog16** [comment]
Created contributions doc in https://github.com/material-components/material-components-web-react/pull/441

**Comment by moog16** [comment]
this is addressed with https://github.com/material-components/material-components-web-react/issues/635
