### ISSUE TITLE
ES modules version

### ISSUE THREAD

**Issue by fjorgemota** [material-components/material-components-web-react#884]
Hey.

I'm testing MDC React here and I observed that every module related to this project on NPM is on...UMD format, so a few optimizations that bundlers (like webpack) do, like concatenation of every module and tree-shaking aren't possible with the dependencies of this package.

It's possible to release a version of each asset based on ES modules, please? I think something like MDC Web (ES Modules with ES5) do is already sufficient...even if a ES modules based purely on ES6 would be nice to have too.

**Comment by moog16** [comment]
@fjorgemota - yes this has been on my wish list for quite some time - https://github.com/material-components/material-components-web-react/issues/699. I am however in the process of exploring rollup instead of webpack in MDC Web. This is in the experimental phase, but once something is decided I plan on porting this over to React as well. For now, the only way you can get "tree-shaking" is via the ts-loader with webpack. I realize a lot of people are not using TypeScript, so this isn't feasible for everyone. 

Since I have #699 open this is a duplicate, and will close this issue. Please feel free to comment and mention me here or on #699 for further discussion. Also I'm open for you to just copy/paste the parts from MDC Web over to gain the ES Modules format. This change requires no tests :) 

Let me know if you'd like to open a PR. Thanks!

**Comment by fjorgemota** [comment]
Whoops. I didn't find #699 before, so...well, sorry for the duplicate.

I see a big advantage in using rollup instead of webpack...I searched about using ES Modules with Webpack but it seems to really not be the ideal tool to do that (rollup seems to be really better in this task). Also, using `ts-loader` didn't allowed me to get tree-shaking support, probably because of the differences in tsconfig.json and on the dev dependencies (as my project uses typescript, too).

I would love to open a PR to help fix #699 but, unfortuntalely, I'm already on a tight deadline with my own project. Maybe later I'm able to help here, as it would bring big advantages related to final size bundle of my project (by avoiding duplicated code like webpack's module functions and probably a few common dependencies in MDC).

Either way, keep the good work, and thanks for the answer. :)

**Comment by moog16** [comment]
Yeah I just need to build some prototypes and defend my case for rollup (as the majority of our eng team agrees with you). This type of project isn't suited well for outside contributions, but thank you for offering! Keep on submitting issues -- we appreciate it!
