### ISSUE TITLE
Closing a Dialog that was rendered from inside a Dialog closes both of them

### ISSUE THREAD

**Issue by ndtreviv** [material-components/material-components-web-react#921]
I have a dialog where users can add search filters (still definitely in development!):
<img width="1987" alt="Screenshot 2019-06-11 at 12 07 24" src="https://user-images.githubusercontent.com/1530653/59267228-8e51d000-8c41-11e9-81f4-5bd4dbd7b49d.png">

One possible filter is a location filter. They click a button to render a map area selector:
<img width="1945" alt="Screenshot 2019-06-11 at 12 07 40" src="https://user-images.githubusercontent.com/1530653/59267243-9578de00-8c41-11e9-979b-6a2f3c26362c.png">

However, when the first dialog closes, the second one also gets closed.

How can I prevent that from happening? All that onClose receives is an action, so I can't prevent event propagation.

Stackblitz: https://stackblitz.com/edit/react-ejnyto

**Comment by moog16** [comment]
@ndtreviv this goes back to the fact that this is not a controlled component. See https://github.com/material-components/material-components-web-react/issues/772 and #785. Because of this, the MDC Web foundation automatically calls notifyClosed on both of the dialogs. 

The easiest work around which may not work for you is to swap out the content of the dialog. Does that work?

**Comment by ndtreviv** [comment]
Gotcha. Can't wait for _that_ guy's PR! 😂

Unfortunately swapping out the content would be super ugly, because it's another layer down, ie:
`Dialog2 -> Filter Field[type = location] -> Dialog2`

I'll give it a go as a workaround

**Comment by moog16** [comment]
Yeah, might not be as beautiful as you'd like it to be. But I'm sure it is possible.

**Comment by moog16** [comment]
Going to close this issue as it is covered in #772 and #785.
